-- MySQL Script generated by MySQL Workbench
-- ter 19 mai 2026 16:07:21
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema concog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `concog` ;

-- -----------------------------------------------------
-- Schema concog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concog` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `concog` ;

-- -----------------------------------------------------
-- Table `concog`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`usuario` ;

CREATE TABLE IF NOT EXISTS `concog`.`usuario` (
  `usuario_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `data_cad` DATETIME NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB
COMMENT = 'Armazone dados do usuário que loga no sistema';


-- -----------------------------------------------------
-- Table `concog`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`cliente` ;

CREATE TABLE IF NOT EXISTS `concog`.`cliente` (
  `cliente_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_fantasia` VARCHAR(200) NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  `data_cad` DATETIME NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB
COMMENT = 'Tabela que armazena os dados base dos clientes que pode ser um contador ou um CNPJ';

CREATE UNIQUE INDEX `cnpj_UNIQUE` ON `concog`.`cliente` (`cnpj` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `concog`.`lancamento_arquivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`lancamento_arquivo` ;

CREATE TABLE IF NOT EXISTS `concog`.`lancamento_arquivo` (
  `lancamento_arquivo_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cliente_id` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `s3_path` VARCHAR(400) NOT NULL COMMENT 'Armazena o path de onde o arquivo foi salvo no S3',
  `data_cad` DATETIME NOT NULL,
  PRIMARY KEY (`lancamento_arquivo_id`),
  CONSTRAINT `fk_lancamento_arquivo_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `concog`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_arquivo_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `concog`.`cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Armazena dados do arquivo que contém os lançamentos';

CREATE UNIQUE INDEX `s3_path_UNIQUE` ON `concog`.`lancamento_arquivo` (`s3_path` ASC) VISIBLE;

CREATE INDEX `fk_lancamento_arquivo_usuario1_idx` ON `concog`.`lancamento_arquivo` (`usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_lancamento_arquivo_cliente1_idx` ON `concog`.`lancamento_arquivo` (`cliente_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `concog`.`lancamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`lancamento` ;

CREATE TABLE IF NOT EXISTS `concog`.`lancamento` (
  `lancamento_id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `lancamento_arquivo_id` BIGINT UNSIGNED NOT NULL,
  `lancamento_dados` JSON NOT NULL COMMENT 'Armazena um JSON com todos os campos e valores de um lançamento',
  `chave_agrupador` CHAR(32) NOT NULL COMMENT 'Armazena o UUID de um grupo de lançamentos que serão analisados juntos no processo do LLM',
  `data_cad` DATETIME NOT NULL,
  `data_atu_llm` DATETIME NULL,
  `data_atu_llm_usuario` DATETIME NULL,
  PRIMARY KEY (`lancamento_id`),
  CONSTRAINT `fk_lancamento_lancamento_arquivo1`
    FOREIGN KEY (`lancamento_arquivo_id`)
    REFERENCES `concog`.`lancamento_arquivo` (`lancamento_arquivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Aramazena todos os lançamentos de um arquivo';

CREATE INDEX `fk_lancamento_lancamento_arquivo1_idx` ON `concog`.`lancamento` (`lancamento_arquivo_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `concog`.`lancamento_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`lancamento_status` ;

CREATE TABLE IF NOT EXISTS `concog`.`lancamento_status` (
  `lancamento_status_id` SMALLINT NOT NULL,
  `descricao_status` VARCHAR(20) NOT NULL COMMENT 'Descrição do status',
  `abreviacao_status` CHAR(1) NOT NULL COMMENT 'Abreviação dos status Conciliado C, Não Conciliado NC e Pendente P',
  PRIMARY KEY (`lancamento_status_id`))
ENGINE = InnoDB
COMMENT = 'Armazena os dados que foram processados para Conciliado, Não Conciliado ou Pendente';

CREATE UNIQUE INDEX `descricao_status_UNIQUE` ON `concog`.`lancamento_status` (`descricao_status` ASC) VISIBLE;

CREATE UNIQUE INDEX `abreviacao_status_UNIQUE` ON `concog`.`lancamento_status` (`abreviacao_status` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `concog`.`arquivo_parser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`arquivo_parser` ;

CREATE TABLE IF NOT EXISTS `concog`.`arquivo_parser` (
  `arquivo_parser_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_parser` VARCHAR(100) NOT NULL COMMENT 'Nome ou Namespace da classe que faz o parser do XLSX',
  `descricao_arquivo_parser` VARCHAR(200) NOT NULL COMMENT 'Descrição do parser',
  PRIMARY KEY (`arquivo_parser_id`))
ENGINE = InnoDB
COMMENT = 'Essa tabela armazena dados que determina os formatos dos arquivos';

CREATE UNIQUE INDEX `nome_classe_UNIQUE` ON `concog`.`arquivo_parser` (`nome_parser` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `concog`.`arquivo_parser_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`arquivo_parser_cliente` ;

CREATE TABLE IF NOT EXISTS `concog`.`arquivo_parser_cliente` (
  `cliente_id` INT UNSIGNED NOT NULL,
  `arquivo_parser_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cliente_id`, `arquivo_parser_id`),
  CONSTRAINT `fk_arquivo_parser_cliente_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `concog`.`cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_arquivo_parser_cliente_arquivo_parser1`
    FOREIGN KEY (`arquivo_parser_id`)
    REFERENCES `concog`.`arquivo_parser` (`arquivo_parser_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_arquivo_parser_cliente_cliente1_idx` ON `concog`.`arquivo_parser_cliente` (`cliente_id` ASC) VISIBLE;

CREATE INDEX `fk_arquivo_parser_cliente_arquivo_parser1_idx` ON `concog`.`arquivo_parser_cliente` (`arquivo_parser_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `concog`.`lancamento_processado_llm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`lancamento_processado_llm` ;

CREATE TABLE IF NOT EXISTS `concog`.`lancamento_processado_llm` (
  `lancamento_procesado_llm_id` BIGINT NOT NULL AUTO_INCREMENT,
  `lancamento_arquivo_id` BIGINT UNSIGNED NOT NULL,
  `lancamento_id` BIGINT UNSIGNED NOT NULL,
  `llm_usado` VARCHAR(40) NOT NULL,
  `lancamento_processado` JSON NOT NULL,
  `data_cad` DATETIME NOT NULL,
  PRIMARY KEY (`lancamento_procesado_llm_id`),
  CONSTRAINT `fk_lancamento_procesado_llm_lancamento1`
    FOREIGN KEY (`lancamento_id`)
    REFERENCES `concog`.`lancamento` (`lancamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_procesado_llm_lancamento_arquivo1`
    FOREIGN KEY (`lancamento_arquivo_id`)
    REFERENCES `concog`.`lancamento_arquivo` (`lancamento_arquivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabela que armazena os lançamentos processados pelo LLM';

CREATE INDEX `fk_lancamento_procesado_llm_lancamento1_idx` ON `concog`.`lancamento_processado_llm` (`lancamento_id` ASC) VISIBLE;

CREATE INDEX `fk_lancamento_procesado_llm_lancamento_arquivo1_idx` ON `concog`.`lancamento_processado_llm` (`lancamento_arquivo_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `concog`.`cliente_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`cliente_usuario` ;

CREATE TABLE IF NOT EXISTS `concog`.`cliente_usuario` (
  `cliente_id` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`cliente_id`, `usuario_id`),
  CONSTRAINT `fk_cliente_usuario_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `concog`.`cliente` (`cliente_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `concog`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cliente_usuario_usuario1_idx` ON `concog`.`cliente_usuario` (`usuario_id` ASC) VISIBLE;

USE `concog` ;

-- -----------------------------------------------------
-- Placeholder table for view `concog`.`vw_lancamento_processado_historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concog`.`vw_lancamento_processado_historico` (`id` INT);

-- -----------------------------------------------------
-- View `concog`.`vw_lancamento_processado_historico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`vw_lancamento_processado_historico`;
DROP VIEW IF EXISTS `concog`.`vw_lancamento_processado_historico` ;
USE `concog`;
CREATE  OR REPLACE VIEW vw_lancamento_processado_historico AS
SELECT 
    lp.*,
    jt.historico_processado
FROM 
    lancamento_processado_llm lp
JOIN 
    JSON_TABLE(
        lp.lancamento_processado,
        '$[*]' COLUMNS (
            historico_processado VARCHAR(255) PATH '$.historico'
        )
    ) AS jt;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `concog`.`lancamento_status`
-- -----------------------------------------------------
START TRANSACTION;
USE `concog`;
INSERT INTO `concog`.`lancamento_status` (`lancamento_status_id`, `descricao_status`, `abreviacao_status`) VALUES (1, 'Conciliado', 'C');
INSERT INTO `concog`.`lancamento_status` (`lancamento_status_id`, `descricao_status`, `abreviacao_status`) VALUES (2, 'Não Conciliado', 'N');
INSERT INTO `concog`.`lancamento_status` (`lancamento_status_id`, `descricao_status`, `abreviacao_status`) VALUES (3, 'Pendente', 'P');

COMMIT;


-- -----------------------------------------------------
-- Data for table `concog`.`arquivo_parser`
-- -----------------------------------------------------
START TRANSACTION;
USE `concog`;
INSERT INTO `concog`.`arquivo_parser` (`arquivo_parser_id`, `nome_parser`, `descricao_arquivo_parser`) VALUES (1, 'concog', 'Planilha padrão do projeto');
INSERT INTO `concog`.`arquivo_parser` (`arquivo_parser_id`, `nome_parser`, `descricao_arquivo_parser`) VALUES (2, 'cwm', 'Planilha padrão da empresa CWM');

COMMIT;

