-- MySQL Script generated by MySQL Workbench
-- seg 09 mar 2026 22:58:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema concog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `concog` ;

-- -----------------------------------------------------
-- Schema concog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concog` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `concog` ;

-- -----------------------------------------------------
-- Table `concog`.`lancamento_arquivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`lancamento_arquivo` ;

CREATE TABLE IF NOT EXISTS `concog`.`lancamento_arquivo` (
  `lancamento_arquivo_id` BIGINT UNSIGNED NOT NULL,
  `s3_path` VARCHAR(400) NOT NULL,
  `data_cad` DATETIME NOT NULL,
  PRIMARY KEY (`lancamento_arquivo_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Armazena dados do arquivo que contém os lançamentos';

CREATE UNIQUE INDEX `s3_path_UNIQUE` ON `concog`.`lancamento_arquivo` (`s3_path` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `concog`.`lancamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`lancamento` ;

CREATE TABLE IF NOT EXISTS `concog`.`lancamento` (
  `lancamento_id` BIGINT UNSIGNED NOT NULL,
  `lancamento_arquivo_id` INT UNSIGNED NOT NULL,
  `lancamento_dados` JSON NOT NULL,
  `data_cad` DATETIME NOT NULL,
  PRIMARY KEY (`lancamento_id`),
  CONSTRAINT `fk_lancamento_lancamento_arquivo1`
    FOREIGN KEY (`lancamento_arquivo_id`)
    REFERENCES `concog`.`lancamento_arquivo` (`lancamento_arquivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Aramazena todos os lançamentos de um arquivo';

CREATE INDEX `fk_lancamento_lancamento_arquivo1_idx` ON `concog`.`lancamento` (`lancamento_arquivo_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `concog`.`lancamento_processado_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`lancamento_processado_status` ;

CREATE TABLE IF NOT EXISTS `concog`.`lancamento_processado_status` (
  `lancamento_processado_status_id` SMALLINT NOT NULL,
  `descricao_status` VARCHAR(20) NOT NULL,
  `abreviacao_status` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`lancamento_processado_status_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `descricao_status_UNIQUE` ON `concog`.`lancamento_processado_status` (`descricao_status` ASC) VISIBLE;

CREATE UNIQUE INDEX `abreviacao_status_UNIQUE` ON `concog`.`lancamento_processado_status` (`abreviacao_status` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `concog`.`lancamento_processado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`lancamento_processado` ;

CREATE TABLE IF NOT EXISTS `concog`.`lancamento_processado` (
  `lancamento_arquivo_id` BIGINT UNSIGNED NOT NULL,
  `lancamento_lancamento_id` BIGINT UNSIGNED NOT NULL,
  `status_llm` SMALLINT NOT NULL COMMENT 'Esse campo recebe o status gerado pelo LLM',
  `status_usuario` SMALLINT NOT NULL DEFAULT 3 COMMENT 'Esse campo recebe o status gerado pelo usuário que é o status definitivo',
  PRIMARY KEY (`lancamento_arquivo_id`, `lancamento_lancamento_id`),
  CONSTRAINT `fk_lancamento_processado_lancamento_arquivo1`
    FOREIGN KEY (`lancamento_arquivo_id`)
    REFERENCES `concog`.`lancamento_arquivo` (`lancamento_arquivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_processado_lancamento1`
    FOREIGN KEY (`lancamento_lancamento_id`)
    REFERENCES `concog`.`lancamento` (`lancamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_processado_lancamento_processado_status1`
    FOREIGN KEY (`status_llm`)
    REFERENCES `concog`.`lancamento_processado_status` (`lancamento_processado_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_processado_lancamento_processado_status2`
    FOREIGN KEY (`status_usuario`)
    REFERENCES `concog`.`lancamento_processado_status` (`lancamento_processado_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_lancamento_processado_lancamento_arquivo1_idx` ON `concog`.`lancamento_processado` (`lancamento_arquivo_id` ASC) VISIBLE;

CREATE INDEX `fk_lancamento_processado_lancamento1_idx` ON `concog`.`lancamento_processado` (`lancamento_lancamento_id` ASC) VISIBLE;

CREATE INDEX `fk_lancamento_processado_lancamento_processado_status1_idx` ON `concog`.`lancamento_processado` (`status_llm` ASC) VISIBLE;

CREATE INDEX `fk_lancamento_processado_lancamento_processado_status2_idx` ON `concog`.`lancamento_processado` (`status_usuario` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `concog`.`lancamento_processado_status`
-- -----------------------------------------------------
START TRANSACTION;
USE `concog`;
INSERT INTO `concog`.`lancamento_processado_status` (`lancamento_processado_status_id`, `descricao_status`, `abreviacao_status`) VALUES (1, 'Conciliado', 'C');
INSERT INTO `concog`.`lancamento_processado_status` (`lancamento_processado_status_id`, `descricao_status`, `abreviacao_status`) VALUES (2, 'Não Conciliado', 'NC');
INSERT INTO `concog`.`lancamento_processado_status` (`lancamento_processado_status_id`, `descricao_status`, `abreviacao_status`) VALUES (3, 'Pendente', 'P');

COMMIT;

