-- MySQL Script generated by MySQL Workbench
-- qui 12 mar 2026 19:34:18
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema concog
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `concog` ;

-- -----------------------------------------------------
-- Schema concog
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concog` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `concog` ;

-- -----------------------------------------------------
-- Table `concog`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`usuario` ;

CREATE TABLE IF NOT EXISTS `concog`.`usuario` (
  `usuario_id` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `login` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `data_cad` DATETIME NOT NULL,
  PRIMARY KEY (`usuario_id`))
ENGINE = InnoDB
COMMENT = 'Armazone dados do usuário que loga no sistema';


-- -----------------------------------------------------
-- Table `concog`.`tipo_arquivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`tipo_arquivo` ;

CREATE TABLE IF NOT EXISTS `concog`.`tipo_arquivo` (
  `tipo_arquivo_id` INT UNSIGNED NOT NULL,
  `classe_tipo_arquivo` VARCHAR(100) NOT NULL COMMENT 'Nome ou Namespace da classe do tipo de arquivo',
  `descricao_tipo_arquivo` VARCHAR(200) NOT NULL COMMENT 'Descrição do tipo de arquivo',
  PRIMARY KEY (`tipo_arquivo_id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `classe_tipo_arquivo_UNIQUE` ON `concog`.`tipo_arquivo` (`classe_tipo_arquivo` ASC) VISIBLE;

CREATE UNIQUE INDEX `descricao_tipo_arquivo_UNIQUE` ON `concog`.`tipo_arquivo` (`descricao_tipo_arquivo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `concog`.`lancamento_arquivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`lancamento_arquivo` ;

CREATE TABLE IF NOT EXISTS `concog`.`lancamento_arquivo` (
  `lancamento_arquivo_id` BIGINT UNSIGNED NOT NULL,
  `tipo_arquivo_id` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `s3_path` VARCHAR(400) NOT NULL COMMENT 'Armazena o path de onde o arquivo foi salvo no S3',
  `data_cad` DATETIME NOT NULL,
  PRIMARY KEY (`lancamento_arquivo_id`),
  CONSTRAINT `fk_lancamento_arquivo_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `concog`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_arquivo_tipo_arquivo1`
    FOREIGN KEY (`tipo_arquivo_id`)
    REFERENCES `concog`.`tipo_arquivo` (`tipo_arquivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Armazena dados do arquivo que contém os lançamentos';

CREATE UNIQUE INDEX `s3_path_UNIQUE` ON `concog`.`lancamento_arquivo` (`s3_path` ASC) VISIBLE;

CREATE INDEX `fk_lancamento_arquivo_usuario1_idx` ON `concog`.`lancamento_arquivo` (`usuario_id` ASC) VISIBLE;

CREATE INDEX `fk_lancamento_arquivo_tipo_arquivo1_idx` ON `concog`.`lancamento_arquivo` (`tipo_arquivo_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `concog`.`lancamento_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`lancamento_status` ;

CREATE TABLE IF NOT EXISTS `concog`.`lancamento_status` (
  `lancamento_status_id` SMALLINT NOT NULL,
  `descricao_status` VARCHAR(20) NOT NULL COMMENT 'Descrição do status',
  `abreviacao_status` VARCHAR(2) NOT NULL COMMENT 'Abreviação dos status Conciliado C, Não Conciliado NC e Pendente P',
  PRIMARY KEY (`lancamento_status_id`))
ENGINE = InnoDB
COMMENT = 'Armazena os dados que foram processados para Conciliado, Não Conciliado ou Pendente';

CREATE UNIQUE INDEX `descricao_status_UNIQUE` ON `concog`.`lancamento_status` (`descricao_status` ASC) VISIBLE;

CREATE UNIQUE INDEX `abreviacao_status_UNIQUE` ON `concog`.`lancamento_status` (`abreviacao_status` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `concog`.`lancamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `concog`.`lancamento` ;

CREATE TABLE IF NOT EXISTS `concog`.`lancamento` (
  `lancamento_id` BIGINT UNSIGNED NOT NULL,
  `lancamento_arquivo_id` BIGINT UNSIGNED NOT NULL,
  `lancamento_status_id_llm` SMALLINT NULL,
  `lancamento_status_id_usuario` SMALLINT NULL,
  `lancamento_dados` JSON NOT NULL COMMENT 'Armazena um JSON com todos os campos e valores de um lançamento',
  `agrupador_llm` CHAR(32) NULL COMMENT 'Armazena o UUID de um grupo de lançamentos que serão analisado juntos',
  `agrupador_usuario` CHAR(32) NULL COMMENT 'Armazena o UUID de um grupo de lançamentos que serão analisado juntos',
  `data_cad` DATETIME NOT NULL,
  `data_atu_llm` DATETIME NULL,
  `data_atu_llm_usuario` DATETIME NULL,
  PRIMARY KEY (`lancamento_id`),
  CONSTRAINT `fk_lancamento_lancamento_arquivo1`
    FOREIGN KEY (`lancamento_arquivo_id`)
    REFERENCES `concog`.`lancamento_arquivo` (`lancamento_arquivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_lancamento_status1`
    FOREIGN KEY (`lancamento_status_id_llm`)
    REFERENCES `concog`.`lancamento_status` (`lancamento_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_lancamento_status2`
    FOREIGN KEY (`lancamento_status_id_usuario`)
    REFERENCES `concog`.`lancamento_status` (`lancamento_status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci
COMMENT = 'Aramazena todos os lançamentos de um arquivo';

CREATE INDEX `fk_lancamento_lancamento_arquivo1_idx` ON `concog`.`lancamento` (`lancamento_arquivo_id` ASC) VISIBLE;

CREATE INDEX `fk_lancamento_lancamento_status1_idx` ON `concog`.`lancamento` (`lancamento_status_id_llm` ASC) VISIBLE;

CREATE INDEX `fk_lancamento_lancamento_status2_idx` ON `concog`.`lancamento` (`lancamento_status_id_usuario` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `concog`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `concog`;
INSERT INTO `concog`.`usuario` (`usuario_id`, `nome`, `login`, `senha`, `data_cad`) VALUES (1, 'Fernando Cervan', 'fcervan', '123456', '2026-03-10 09:02:26');

COMMIT;


-- -----------------------------------------------------
-- Data for table `concog`.`tipo_arquivo`
-- -----------------------------------------------------
START TRANSACTION;
USE `concog`;
INSERT INTO `concog`.`tipo_arquivo` (`tipo_arquivo_id`, `classe_tipo_arquivo`, `descricao_tipo_arquivo`) VALUES (1, 'cwm', 'Classe padrão do projeto que se baseia na planilha da CWM');

COMMIT;


-- -----------------------------------------------------
-- Data for table `concog`.`lancamento_arquivo`
-- -----------------------------------------------------
START TRANSACTION;
USE `concog`;
INSERT INTO `concog`.`lancamento_arquivo` (`lancamento_arquivo_id`, `tipo_arquivo_id`, `usuario_id`, `s3_path`, `data_cad`) VALUES (1, 1, 1, 'teste', '2026-03-12 18:45:00');

COMMIT;


-- -----------------------------------------------------
-- Data for table `concog`.`lancamento_status`
-- -----------------------------------------------------
START TRANSACTION;
USE `concog`;
INSERT INTO `concog`.`lancamento_status` (`lancamento_status_id`, `descricao_status`, `abreviacao_status`) VALUES (1, 'Conciliado', 'C');
INSERT INTO `concog`.`lancamento_status` (`lancamento_status_id`, `descricao_status`, `abreviacao_status`) VALUES (2, 'Não Conciliado', 'NC');
INSERT INTO `concog`.`lancamento_status` (`lancamento_status_id`, `descricao_status`, `abreviacao_status`) VALUES (3, 'Pendente', 'P');

COMMIT;


-- -----------------------------------------------------
-- Data for table `concog`.`lancamento`
-- -----------------------------------------------------
START TRANSACTION;
USE `concog`;
INSERT INTO `concog`.`lancamento` (`lancamento_id`, `lancamento_arquivo_id`, `lancamento_status_id_llm`, `lancamento_status_id_usuario`, `lancamento_dados`, `agrupador_llm`, `agrupador_usuario`, `data_cad`, `data_atu_llm`, `data_atu_llm_usuario`) VALUES (1, 1, NULL, NULL, '{\"HISTORICO\":\"MULTA VEICULO RUJ5C38 AIT N007086405 DATA \",\"DEBITO\":\"0,00\",\"CREDITO\":\"312,38\",\"SALDO\":\"-312,38\",\"LANCAMENTO_ID\":234}', NULL, NULL, '2026-03-12 19:20:25', NULL, NULL);
INSERT INTO `concog`.`lancamento` (`lancamento_id`, `lancamento_arquivo_id`, `lancamento_status_id_llm`, `lancamento_status_id_usuario`, `lancamento_dados`, `agrupador_llm`, `agrupador_usuario`, `data_cad`, `data_atu_llm`, `data_atu_llm_usuario`) VALUES (2, 1, NULL, NULL, '{\"HISTORICO\":\"LOCACAO VEICULO VOYAGEM RUI6F76\",\"DEBITO\":\"0,00\",\"CREDITO\":\"1.790,00\",\"SALDO\":\"-2.102,38\",\"LANCAMENTO_ID\":235}', NULL, NULL, '2026-03-12 19:20:25', NULL, NULL);
INSERT INTO `concog`.`lancamento` (`lancamento_id`, `lancamento_arquivo_id`, `lancamento_status_id_llm`, `lancamento_status_id_usuario`, `lancamento_dados`, `agrupador_llm`, `agrupador_usuario`, `data_cad`, `data_atu_llm`, `data_atu_llm_usuario`) VALUES (3, 1, NULL, NULL, '{\"HISTORICO\":\"FAT 813074 LOCACAO VEICULOS VOUAGE RUH 2I62, HB20 RUJ5C36 E HB20 RUJ5C38\",\"DEBITO\":\"0,00\",\"CREDITO\":\"5.327,00\",\"SALDO\":\"-7.429,38\",\"LANCAMENTO_ID\":236}', NULL, NULL, '2026-03-12 19:20:25', NULL, NULL);
INSERT INTO `concog`.`lancamento` (`lancamento_id`, `lancamento_arquivo_id`, `lancamento_status_id_llm`, `lancamento_status_id_usuario`, `lancamento_dados`, `agrupador_llm`, `agrupador_usuario`, `data_cad`, `data_atu_llm`, `data_atu_llm_usuario`) VALUES (4, 1, NULL, NULL, '{\"HISTORICO\":\"FAT 811709 REAJUSTE CONTRATO VEICULO RUH2I63\",\"DEBITO\":\"0,00\",\"CREDITO\":\"360,00\",\"SALDO\":\"-7.789,38\",\"LANCAMENTO_ID\":237}', NULL, NULL, '2026-03-12 19:20:25', NULL, NULL);
INSERT INTO `concog`.`lancamento` (`lancamento_id`, `lancamento_arquivo_id`, `lancamento_status_id_llm`, `lancamento_status_id_usuario`, `lancamento_dados`, `agrupador_llm`, `agrupador_usuario`, `data_cad`, `data_atu_llm`, `data_atu_llm_usuario`) VALUES (5, 1, NULL, NULL, '{\"HISTORICO\":\"FAT 811708 REAJUSTE CONTRATO LOCACAO VEIUCLOS RUI6F76, RUJ5C36 E RUJ5C38 USECAR\",\"DEBITO\":\"0,00\",\"CREDITO\":\"1.055,00\",\"SALDO\":\"-8.844,38\",\"LANCAMENTO_ID\":238}', NULL, NULL, '2026-03-12 19:20:25', NULL, NULL);
INSERT INTO `concog`.`lancamento` (`lancamento_id`, `lancamento_arquivo_id`, `lancamento_status_id_llm`, `lancamento_status_id_usuario`, `lancamento_dados`, `agrupador_llm`, `agrupador_usuario`, `data_cad`, `data_atu_llm`, `data_atu_llm_usuario`) VALUES (6, 1, NULL, NULL, '{\"HISTORICO\":\"FAT.811980 USECAR LOCADOR DE VEICULOS S A - PAGAMENTO FORNECEDOR - FAT.811980 LOCAÇÃO 1 VEÍCULO - RUI-6F76 (WOLNEY)\",\"DEBITO\":\"1.790,00\",\"CREDITO\":\"0,00\",\"SALDO\":\"-7.054,38\",\"LANCAMENTO_ID\":239}', NULL, NULL, '2026-03-12 19:20:25', NULL, NULL);
INSERT INTO `concog`.`lancamento` (`lancamento_id`, `lancamento_arquivo_id`, `lancamento_status_id_llm`, `lancamento_status_id_usuario`, `lancamento_dados`, `agrupador_llm`, `agrupador_usuario`, `data_cad`, `data_atu_llm`, `data_atu_llm_usuario`) VALUES (7, 1, NULL, NULL, '{\"HISTORICO\":\"ND.812022 USECAR LOCADOR DE VEICULOS S A - PAGAMENTO FORNECEDOR - ND.812022 MULTAS VEICULOS LOCAÇÃO RUJ5C38 - 07:24\",\"DEBITO\":\"312,38\",\"CREDITO\":\"0,00\",\"SALDO\":\"-6.742,00\",\"LANCAMENTO_ID\":240}', NULL, NULL, '2026-03-12 19:20:25', NULL, NULL);
INSERT INTO `concog`.`lancamento` (`lancamento_id`, `lancamento_arquivo_id`, `lancamento_status_id_llm`, `lancamento_status_id_usuario`, `lancamento_dados`, `agrupador_llm`, `agrupador_usuario`, `data_cad`, `data_atu_llm`, `data_atu_llm_usuario`) VALUES (8, 1, NULL, NULL, '{\"HISTORICO\":\"FAT.811708 USECAR LOCADOR DE VEICULOS S A - PAGAMENTO FORNECEDOR - FAT.811708 REAJUSTE CONTRATUAL RETROATIVO VEICULOS\",\"DEBITO\":\"1.055,00\",\"CREDITO\":\"0,00\",\"SALDO\":\"-5.687,00\",\"LANCAMENTO_ID\":241}', NULL, NULL, '2026-03-12 19:20:25', NULL, NULL);
INSERT INTO `concog`.`lancamento` (`lancamento_id`, `lancamento_arquivo_id`, `lancamento_status_id_llm`, `lancamento_status_id_usuario`, `lancamento_dados`, `agrupador_llm`, `agrupador_usuario`, `data_cad`, `data_atu_llm`, `data_atu_llm_usuario`) VALUES (9, 1, NULL, NULL, '{\"HISTORICO\":\"FAT.811709 USECAR LOCADOR DE VEICULOS S A - PAGAMENTO FORNECEDOR - FAT.811709 REAJUSTE CONTRATUAL RETROATIVO VEICULOS\",\"DEBITO\":\"360,00\",\"CREDITO\":\"0,00\",\"SALDO\":\"-5.327,00\",\"LANCAMENTO_ID\":242}', NULL, NULL, '2026-03-12 19:20:25', NULL, NULL);
INSERT INTO `concog`.`lancamento` (`lancamento_id`, `lancamento_arquivo_id`, `lancamento_status_id_llm`, `lancamento_status_id_usuario`, `lancamento_dados`, `agrupador_llm`, `agrupador_usuario`, `data_cad`, `data_atu_llm`, `data_atu_llm_usuario`) VALUES (10, 1, NULL, NULL, '{\"HISTORICO\":\"FAT.813074 USECAR LOCADOR DE VEICULOS S A - PAGAMENTO FORNECEDOR - FAT.813074 LOCAÇÃO 3 VEÍCULOS - RUH2I63 RUJ5C36 RUJ5C38\",\"DEBITO\":\"5.327,00\",\"CREDITO\":\"0,00\",\"SALDO\":\"-0,00\",\"LANCAMENTO_ID\":243}', NULL, NULL, '2026-03-12 19:20:25', NULL, NULL);
INSERT INTO `concog`.`lancamento` (`lancamento_id`, `lancamento_arquivo_id`, `lancamento_status_id_llm`, `lancamento_status_id_usuario`, `lancamento_dados`, `agrupador_llm`, `agrupador_usuario`, `data_cad`, `data_atu_llm`, `data_atu_llm_usuario`) VALUES (11, 1, NULL, NULL, '{\"HISTORICO\":\"FAT.814246 USECAR LOCADOR DE VEICULOS S A - PAGAMENTO FORNECEDOR - FAT.814246 LOCAÇÃO 1 VEÍCULO - RUI-6F76 (WOLNEY)\",\"DEBITO\":\"1.790,00\",\"CREDITO\":\"0,00\",\"SALDO\":\"1.790,00\",\"LANCAMENTO_ID\":244}', NULL, NULL, '2026-03-12 19:20:25', NULL, NULL);

COMMIT;

