-- MySQL Script generated by MySQL Workbench
-- seg 09 mar 2026 20:20:35
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cadin
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cadin` ;

-- -----------------------------------------------------
-- Schema cadin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cadin` ;
USE `cadin` ;

-- -----------------------------------------------------
-- Table `cadin`.`escritorio_contabil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadin`.`escritorio_contabil` ;

CREATE TABLE IF NOT EXISTS `cadin`.`escritorio_contabil` (
  `escritorio_contabil_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_fantasia` VARCHAR(150) NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  `data_cad` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`escritorio_contabil_id`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Tabela com dados do cliente';


-- -----------------------------------------------------
-- Table `cadin`.`tipo_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadin`.`tipo_usuario` ;

CREATE TABLE IF NOT EXISTS `cadin`.`tipo_usuario` (
  `tipo_usuario_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipo_usuario_id`),
  UNIQUE INDEX `descricao_UNIQUE` (`descricao` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadin`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadin`.`usuario` ;

CREATE TABLE IF NOT EXISTS `cadin`.`usuario` (
  `usuario_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipo_usuario_id` INT UNSIGNED NOT NULL,
  `escritorio_contabil_id` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `ativo` TINYINT NOT NULL,
  `data_cad` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuario_id`, `tipo_usuario_id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  INDEX `idx_usuario_login_senha` (`login` ASC, `senha` ASC) VISIBLE,
  INDEX `fk_usuario_cliente_idx` (`escritorio_contabil_id` ASC) VISIBLE,
  INDEX `fk_usuario_tipo_usuario1_idx` (`tipo_usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_cliente`
    FOREIGN KEY (`escritorio_contabil_id`)
    REFERENCES `cadin`.`escritorio_contabil` (`escritorio_contabil_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_tipo_usuario1`
    FOREIGN KEY (`tipo_usuario_id`)
    REFERENCES `cadin`.`tipo_usuario` (`tipo_usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabela com dados do usuário';


-- -----------------------------------------------------
-- Table `cadin`.`empresa_contabilizada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadin`.`empresa_contabilizada` ;

CREATE TABLE IF NOT EXISTS `cadin`.`empresa_contabilizada` (
  `empresa_contabilizada_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `escritorio_contabil_id` INT UNSIGNED NOT NULL,
  `nome_fantasia` VARCHAR(150) NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  `codigo_externo` VARCHAR(100) NULL COMMENT 'Armazena um código que possa identificar essa empresa cliente no escritório',
  `data_cad` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`empresa_contabilizada_id`),
  INDEX `fk_empresa_contabilizada_cliente1_idx` (`escritorio_contabil_id` ASC) VISIBLE,
  CONSTRAINT `fk_empresa_contabilizada_cliente1`
    FOREIGN KEY (`escritorio_contabil_id`)
    REFERENCES `cadin`.`escritorio_contabil` (`escritorio_contabil_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadin`.`status_lancamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadin`.`status_lancamento` ;

CREATE TABLE IF NOT EXISTS `cadin`.`status_lancamento` (
  `status_lancamento_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`status_lancamento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cadin`.`lancamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cadin`.`lancamento` ;

CREATE TABLE IF NOT EXISTS `cadin`.`lancamento` (
  `lancamento_id` BIGINT UNSIGNED NOT NULL,
  `empresa_contabilizada_id` INT UNSIGNED NOT NULL,
  `status_lancamento_id` INT UNSIGNED NOT NULL,
  `usuario_id` INT UNSIGNED NOT NULL,
  `data_cad` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`lancamento_id`),
  INDEX `fk_lancamento_empresa_contabilizada1_idx` (`empresa_contabilizada_id` ASC) VISIBLE,
  INDEX `fk_lancamento_status_lancamento1_idx` (`status_lancamento_id` ASC) VISIBLE,
  INDEX `fk_lancamento_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_lancamento_empresa_contabilizada1`
    FOREIGN KEY (`empresa_contabilizada_id`)
    REFERENCES `cadin`.`empresa_contabilizada` (`empresa_contabilizada_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_status_lancamento1`
    FOREIGN KEY (`status_lancamento_id`)
    REFERENCES `cadin`.`status_lancamento` (`status_lancamento_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lancamento_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `cadin`.`usuario` (`usuario_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `cadin`.`escritorio_contabil`
-- -----------------------------------------------------
START TRANSACTION;
USE `cadin`;
INSERT INTO `cadin`.`escritorio_contabil` (`escritorio_contabil_id`, `nome_fantasia`, `cnpj`, `data_cad`) VALUES (1, 'CWM', '21310000000168', '2025-06-18 22:19:13');

COMMIT;


-- -----------------------------------------------------
-- Data for table `cadin`.`tipo_usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `cadin`;
INSERT INTO `cadin`.`tipo_usuario` (`tipo_usuario_id`, `descricao`) VALUES (1, 'Admin');
INSERT INTO `cadin`.`tipo_usuario` (`tipo_usuario_id`, `descricao`) VALUES (2, 'Admin Cliente');
INSERT INTO `cadin`.`tipo_usuario` (`tipo_usuario_id`, `descricao`) VALUES (3, 'Usuário Cliente');

COMMIT;


-- -----------------------------------------------------
-- Data for table `cadin`.`usuario`
-- -----------------------------------------------------
START TRANSACTION;
USE `cadin`;
INSERT INTO `cadin`.`usuario` (`usuario_id`, `tipo_usuario_id`, `escritorio_contabil_id`, `nome`, `login`, `senha`, `ativo`, `data_cad`) VALUES (1, DEFAULT, 1, 'Caetano', 'caetano', '123456', 1, '2025-06-18 22:19:13');

COMMIT;


-- -----------------------------------------------------
-- Data for table `cadin`.`status_lancamento`
-- -----------------------------------------------------
START TRANSACTION;
USE `cadin`;
INSERT INTO `cadin`.`status_lancamento` (`status_lancamento_id`, `descricao`) VALUES (1, 'Conciliado');
INSERT INTO `cadin`.`status_lancamento` (`status_lancamento_id`, `descricao`) VALUES (2, 'Pendente');
INSERT INTO `cadin`.`status_lancamento` (`status_lancamento_id`, `descricao`) VALUES (3, 'Não Conciliado');
INSERT INTO `cadin`.`status_lancamento` (`status_lancamento_id`, `descricao`) VALUES (4, 'Conciliado Parcialmente');
INSERT INTO `cadin`.`status_lancamento` (`status_lancamento_id`, `descricao`) VALUES (5, 'Indefinido');

COMMIT;

